[project]
name = "neurotheatre-ezmsg"
version = "0.1.0"
description = "This repo has EzMsg implementation for neurotheatre project application"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ezmsg",
    "numpy",
    "scipy",
    "wheel",
    "pyaudio",
    "mido"
]
